openapi: 3.0.0

info:
  version: 0.0.1
  title: Libertya REST API
  description: Libertya REST API para la gestion y procesamiento de entidades y documentos

tags:
  - name: "LYRESTAPI"

security:
  - jwtAuth: []

components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
  /v1.0/products:
    $ref: ./paths/products.yaml
  /v1.0/products/{id}:
    $ref: ./paths/products_id.yaml
  /v1.0/bpartners:
    $ref: ./paths/bpartners.yaml
  /v1.0/bpartners/{id}:
    $ref: ./paths/bpartners_id.yaml
  /v1.0/invoices:
    $ref: ./paths/invoices.yaml
  /v1.0/invoices/{id}:
    $ref: ./paths/invoices_id.yaml
  /v1.0/invoices/{id}/process:
    $ref: ./paths/invoices_id_process.yaml
  /v1.0/invoicelines:
    $ref: ./paths/invoicelines.yaml
  /v1.0/invoicelines/{id}:
    $ref: ./paths/invoicelines_id.yaml
  /v1.0/orders:
    $ref: ./paths/orders.yaml
  /v1.0/orders/{id}:
    $ref: ./paths/orders_id.yaml
  /v1.0/orders/{id}/process:
    $ref: ./paths/orders_id_process.yaml
  /v1.0/orderlines:
    $ref: ./paths/orderlines.yaml
  /v1.0/orderlines/{id}:
    $ref: ./paths/orderlines_id.yaml
  /v1.0/inouts:
    $ref: ./paths/inouts.yaml
  /v1.0/inouts/{id}:
    $ref: ./paths/inouts_id.yaml
  /v1.0/inouts/{id}/process:
    $ref: ./paths/inouts_id_process.yaml
  /v1.0/inoutlines:
    $ref: ./paths/inoutlines.yaml
  /v1.0/inoutlines/{id}:
    $ref: ./paths/inoutlines_id.yaml
  /v1.0/payments:
    $ref: ./paths/payments.yaml
  /v1.0/payments/{id}:
    $ref: ./paths/payments_id.yaml
  /v1.0/payments/{id}/process:
    $ref: ./paths/payments_id_process.yaml
  /v1.0/cashlines:
    $ref: ./paths/cashlines.yaml
  /v1.0/cashlines/{id}:
    $ref: ./paths/cashlines_id.yaml
  /v1.0/cashlines/{id}/process:
    $ref: ./paths/cashlines_id_process.yaml
  /v1.0/allocations:
    $ref: ./paths/allocations.yaml
  /v1.0/allocations/{id}:
    $ref: ./paths/allocations_id.yaml
  /v1.0/allocations/{id}/process:
    $ref: ./paths/allocations_id_process.yaml
  /v1.0/allocationlines:
    $ref: ./paths/allocationlines.yaml
  /v1.0/allocationlines/{id}:
    $ref: ./paths/allocationlines_id.yaml
  /v1.0/productprices:
    $ref: ./paths/productprices.yaml
  /v1.0/productprices/{idProduct}/{idPriceListVersion}:
    $ref: ./paths/productprices_id_id.yaml
  /v1.0/storages:
    $ref: ./paths/storages.yaml
  /v1.0/storages/{idProduct}:
    $ref: ./paths/storages_id.yaml
  /v1.0/storages/{idProduct}/{idLocator}:
    $ref: ./paths/storages_id_id.yaml
  /v1.0/inventories:
    $ref: ./paths/inventories.yaml
  /v1.0/inventories/{id}:
    $ref: ./paths/inventories_id.yaml
  /v1.0/inventories/{id}/process:
    $ref: ./paths/inventories_id_process.yaml
  /v1.0/inventorylines:
    $ref: ./paths/inventorylines.yaml
  /v1.0/inventorylines/{id}:
    $ref: ./paths/inventorylines_id.yaml
  /v1.0/locations:
    $ref: ./paths/locations.yaml
  /v1.0/locations/{id}:
    $ref: ./paths/locations_id.yaml
  /v1.0/bpartnerlocations:
    $ref: ./paths/bpartnerlocations.yaml
  /v1.0/bpartnerlocations/{id}:
    $ref: ./paths/bpartnerlocations_id.yaml
  /v1.0/users:
    $ref: ./paths/users.yaml
  /v1.0/users/{id}:
    $ref: ./paths/users_id.yaml
  /v1.0/productlines:
    $ref: ./paths/productlines.yaml
  /v1.0/productlines/{id}:
    $ref: ./paths/productlines_id.yaml
  /v1.0/productgamas:
    $ref: ./paths/productgamas.yaml
  /v1.0/productgamas/{id}:
    $ref: ./paths/productgamas_id.yaml
  /v1.0/productcategories:
    $ref: ./paths/productcategories.yaml
  /v1.0/productcategories/{id}:
    $ref: ./paths/productcategories_id.yaml
  /v1.0/productfamilies:
    $ref: ./paths/productfamilies.yaml
  /v1.0/productfamilies/{id}:
    $ref: ./paths/productfamilies_id.yaml
  /v1.0/taxcategories:
    $ref: ./paths/taxcategories.yaml
  /v1.0/taxcategories/{id}:
    $ref: ./paths/taxcategories_id.yaml
  /v1.0/taxes:
    $ref: ./paths/taxes.yaml
  /v1.0/taxes/{id}:
    $ref: ./paths/taxes_id.yaml
  /v1.0/doctypes:
    $ref: ./paths/doctypes.yaml
  /v1.0/doctypes/{id}:
    $ref: ./paths/doctypes_id.yaml
  /v1.0/orgs:
    $ref: ./paths/orgs.yaml
  /v1.0/orgs/{id}:
    $ref: ./paths/orgs_id.yaml
  /v1.0/orgpercepcions:
    $ref: ./paths/orgpercepcions.yaml
  /v1.0/orgpercepcions/{id}:
    $ref: ./paths/orgpercepcions_id.yaml
  /v1.0/pos:
    $ref: ./paths/pos.yaml
  /v1.0/pos/{id}:
    $ref: ./paths/pos_id.yaml
  /v1.0/pospaymentmediums:
    $ref: ./paths/pospaymentmediums.yaml
  /v1.0/pospaymentmediums/{id}:
    $ref: ./paths/pospaymentmediums_id.yaml
  /v1.0/paymentterms:
    $ref: ./paths/paymentterms.yaml
  /v1.0/paymentterms/{id}:
    $ref: ./paths/paymentterms_id.yaml
  /v1.0/payschedules:
    $ref: ./paths/payschedules.yaml
  /v1.0/payschedules/{id}:
    $ref: ./paths/payschedules_id.yaml
  /v1.0/letrascomprobante:
    $ref: ./paths/letrascomprobante.yaml
  /v1.0/letrascomprobante/{id}:
    $ref: ./paths/letrascomprobante_id.yaml
  /v1.0/letrasaceptaiva:
    $ref: ./paths/letrasaceptaiva.yaml
  /v1.0/letrasaceptaiva/{id}:
    $ref: ./paths/letrasaceptaiva_id.yaml
  /v1.0/pricelists:
    $ref: ./paths/pricelists.yaml
  /v1.0/pricelists/{id}:
    $ref: ./paths/pricelists_id.yaml
  /v1.0/pricelistversions:
    $ref: ./paths/pricelistversions.yaml
  /v1.0/pricelistversions/{id}:
    $ref: ./paths/pricelistversions_id.yaml
  /v1.0/banks:
    $ref: ./paths/banks.yaml
  /v1.0/banks/{id}:
    $ref: ./paths/banks_id.yaml
  /v1.0/bankaccounts:
    $ref: ./paths/bankaccounts.yaml
  /v1.0/bankaccounts/{id}:
    $ref: ./paths/bankaccounts_id.yaml
  /v1.0/uoms:
    $ref: ./paths/uoms.yaml
  /v1.0/uoms/{id}:
    $ref: ./paths/uoms_id.yaml
  /v1.0/currencies:
    $ref: ./paths/currencies.yaml
  /v1.0/currencies/{id}:
    $ref: ./paths/currencies_id.yaml
  /v1.0/conversionrates:
    $ref: ./paths/conversionrates.yaml
  /v1.0/conversionrates/{id}:
    $ref: ./paths/conversionrates_id.yaml
  /v1.0/cashbooks:
    $ref: ./paths/cashbooks.yaml
  /v1.0/cashbooks/{id}:
    $ref: ./paths/cashbooks_id.yaml
  /v1.0/cash:
    $ref: ./paths/cash.yaml
  /v1.0/cash/{id}:
    $ref: ./paths/cash_id.yaml
  /v1.0/cash/{id}/process:
    $ref: ./paths/cash_id_process.yaml
  /v1.0/documentdiscounts:
    $ref: ./paths/documentdiscounts.yaml
  /v1.0/documentdiscounts/{id}:
    $ref: ./paths/documentdiscounts_id.yaml
  /v1.0/discountschemas:
    $ref: ./paths/discountschemas.yaml
  /v1.0/discountschemas/{id}:
    $ref: ./paths/discountschemas_id.yaml
  /v1.0/discountschemabreaks:
    $ref: ./paths/discountschemabreaks.yaml
  /v1.0/discountschemabreaks/{id}:
    $ref: ./paths/discountschemabreaks_id.yaml
  /v1.0/discountconfigs:
    $ref: ./paths/discountconfigs.yaml
  /v1.0/discountconfigs/{id}:
    $ref: ./paths/discountconfigs_id.yaml
