openapi: 3.0.0

info:
  version: 0.0.1
  title: Libertya REST API
  description: Libertya REST API para la gestion y procesamiento de entidades y documentos

tags:
  - name: "LYRESTAPI"

paths:
  /v1.0/products:
    $ref: ./paths/products.yaml
  /v1.0/products/{id}:
    $ref: ./paths/products_id.yaml
  /v1.0/bpartners:
    $ref: ./paths/bpartners.yaml
  /v1.0/bpartners/{id}:
    $ref: ./paths/bpartners_id.yaml
  /v1.0/invoices:
    $ref: ./paths/invoices.yaml
  /v1.0/invoices/{id}:
    $ref: ./paths/invoices_id.yaml
  /v1.0/invoices/{id}/process:
    $ref: ./paths/invoices_id_process.yaml
  /v1.0/orders:
    $ref: ./paths/orders.yaml
  /v1.0/orders/{id}:
    $ref: ./paths/orders_id.yaml
  /v1.0/orders/{id}/process:
    $ref: ./paths/orders_id_process.yaml
  /v1.0/inouts:
    $ref: ./paths/inouts.yaml
  /v1.0/inouts/{id}:
    $ref: ./paths/inouts_id.yaml
  /v1.0/inouts/{id}/process:
    $ref: ./paths/inouts_id_process.yaml
  /v1.0/payments:
    $ref: ./paths/payments.yaml
  /v1.0/payments/{id}:
    $ref: ./paths/payments_id.yaml
  /v1.0/payments/{id}/process:
    $ref: ./paths/payments_id_process.yaml
  /v1.0/cashlines:
    $ref: ./paths/cashlines.yaml
  /v1.0/cashlines/{id}:
    $ref: ./paths/cashlines_id.yaml
  /v1.0/cashlines/{id}/process:
    $ref: ./paths/cashlines_id_process.yaml
  /v1.0/allocations:
    $ref: ./paths/allocations.yaml
  /v1.0/allocations/{id}:
    $ref: ./paths/allocations_id.yaml
  /v1.0/allocations/{id}/process:
    $ref: ./paths/allocations_id_process.yaml
