openapi: 3.0.0

info:
  version: 0.0.1
  title: Libertya REST API
  description: Libertya REST API para la gestion y procesamiento de entidades y documentos

tags:
  - name: "LYRESTAPI"

security:
  - jwtAuth: []

components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
  /v1.0/products:
    $ref: ./paths/products.yaml
  /v1.0/products/{id}:
    $ref: ./paths/products_id.yaml
  /v1.0/bpartners:
    $ref: ./paths/bpartners.yaml
  /v1.0/bpartners/{id}:
    $ref: ./paths/bpartners_id.yaml
  /v1.0/invoices:
    $ref: ./paths/invoices.yaml
  /v1.0/invoices/{id}:
    $ref: ./paths/invoices_id.yaml
  /v1.0/invoices/{id}/process:
    $ref: ./paths/invoices_id_process.yaml
  /v1.0/invoicelines:
    $ref: ./paths/invoicelines.yaml
  /v1.0/invoicelines/{id}:
    $ref: ./paths/invoicelines_id.yaml
  /v1.0/orders:
    $ref: ./paths/orders.yaml
  /v1.0/orders/{id}:
    $ref: ./paths/orders_id.yaml
  /v1.0/orders/{id}/process:
    $ref: ./paths/orders_id_process.yaml
  /v1.0/orderlines:
    $ref: ./paths/orderlines.yaml
  /v1.0/orderlines/{id}:
    $ref: ./paths/orderlines_id.yaml
  /v1.0/inouts:
    $ref: ./paths/inouts.yaml
  /v1.0/inouts/{id}:
    $ref: ./paths/inouts_id.yaml
  /v1.0/inouts/{id}/process:
    $ref: ./paths/inouts_id_process.yaml
  /v1.0/inoutlines:
    $ref: ./paths/inoutlines.yaml
  /v1.0/inoutlines/{id}:
    $ref: ./paths/inoutlines_id.yaml
  /v1.0/payments:
    $ref: ./paths/payments.yaml
  /v1.0/payments/{id}:
    $ref: ./paths/payments_id.yaml
  /v1.0/payments/{id}/process:
    $ref: ./paths/payments_id_process.yaml
  /v1.0/cashlines:
    $ref: ./paths/cashlines.yaml
  /v1.0/cashlines/{id}:
    $ref: ./paths/cashlines_id.yaml
  /v1.0/cashlines/{id}/process:
    $ref: ./paths/cashlines_id_process.yaml
  /v1.0/allocations:
    $ref: ./paths/allocations.yaml
  /v1.0/allocations/{id}:
    $ref: ./paths/allocations_id.yaml
  /v1.0/allocations/{id}/process:
    $ref: ./paths/allocations_id_process.yaml
  /v1.0/allocationlines:
    $ref: ./paths/allocationlines.yaml
  /v1.0/allocationlines/{id}:
    $ref: ./paths/allocationlines_id.yaml
  /v1.0/productprices:
    $ref: ./paths/productprices.yaml
  /v1.0/productprices/{idProduct}/{idPriceListVersion}:
    $ref: ./paths/productprices_id_id.yaml
  /v1.0/storages:
    $ref: ./paths/storages.yaml
  /v1.0/storages/{idProduct}:
    $ref: ./paths/storages_id.yaml
  /v1.0/storages/{idProduct}/{idLocator}:
    $ref: ./paths/storages_id_id.yaml
  /v1.0/inventories:
    $ref: ./paths/inventories.yaml
  /v1.0/inventories/{id}:
    $ref: ./paths/inventories_id.yaml
  /v1.0/inventories/{id}/process:
    $ref: ./paths/inventories_id_process.yaml
  /v1.0/inventorylines:
    $ref: ./paths/inventorylines.yaml
  /v1.0/inventorylines/{id}:
    $ref: ./paths/inventorylines_id.yaml
  /v1.0/locations:
    $ref: ./paths/locations.yaml
  /v1.0/locations/{id}:
    $ref: ./paths/locations_id.yaml
  /v1.0/bpartnerlocations:
    $ref: ./paths/bpartnerlocations.yaml
  /v1.0/bpartnerlocations/{id}:
    $ref: ./paths/bpartnerlocations_id.yaml