openapi: 3.0.0

info:
  version: 0.0.1
  title: Libertya REST API
  description: Libertya REST API para la gestion y procesamiento de entidades y documentos

tags:
  - name: "LYRESTAPI"

security:
  - jwtAuth: []

components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


paths:
# operative end-points
  /v1.0/products:
    $ref: ./paths/products.yaml
  /v1.0/products/{id}:
    $ref: ./paths/products_id.yaml
  /v1.0/bpartners:
    $ref: ./paths/bpartners.yaml
  /v1.0/bpartners/{id}:
    $ref: ./paths/bpartners_id.yaml
  /v1.0/invoices:
    $ref: ./paths/invoices.yaml
  /v1.0/invoices/{id}:
    $ref: ./paths/invoices_id.yaml
  /v1.0/invoices/{id}/process:
    $ref: ./paths/invoices_id_process.yaml
  /v1.0/invoices/{id}/print:
    $ref: ./paths/invoices_id_print.yaml
  /v1.0/invoicelines:
    $ref: ./paths/invoicelines.yaml
  /v1.0/invoicelines/{id}:
    $ref: ./paths/invoicelines_id.yaml
  /v1.0/invoicetaxes:
    $ref: ./paths/invoicetaxes.yaml
  /v1.0/invoicetaxes/{idInvoice}/{idTax}:
    $ref: ./paths/invoicetaxes_id_id.yaml
  /v1.0/orders:
    $ref: ./paths/orders.yaml
  /v1.0/orders/{id}:
    $ref: ./paths/orders_id.yaml
  /v1.0/orders/{id}/process:
    $ref: ./paths/orders_id_process.yaml
  /v1.0/orderlines:
    $ref: ./paths/orderlines.yaml
  /v1.0/orderlines/{id}:
    $ref: ./paths/orderlines_id.yaml
  /v1.0/ordertaxes:
    $ref: ./paths/ordertaxes.yaml
  /v1.0/ordertaxes/{idOrder}/{idTax}:
    $ref: ./paths/ordertaxes_id_id.yaml
  /v1.0/inouts:
    $ref: ./paths/inouts.yaml
  /v1.0/inouts/{id}:
    $ref: ./paths/inouts_id.yaml
  /v1.0/inouts/{id}/process:
    $ref: ./paths/inouts_id_process.yaml
  /v1.0/inoutlines:
    $ref: ./paths/inoutlines.yaml
  /v1.0/inoutlines/{id}:
    $ref: ./paths/inoutlines_id.yaml
  /v1.0/payments:
    $ref: ./paths/payments.yaml
  /v1.0/payments/{id}:
    $ref: ./paths/payments_id.yaml
  /v1.0/payments/{id}/process:
    $ref: ./paths/payments_id_process.yaml
  /v1.0/cashlines:
    $ref: ./paths/cashlines.yaml
  /v1.0/cashlines/{id}:
    $ref: ./paths/cashlines_id.yaml
  /v1.0/cashlines/{id}/process:
    $ref: ./paths/cashlines_id_process.yaml
  /v1.0/allocations:
    $ref: ./paths/allocations.yaml
  /v1.0/allocations/{id}:
    $ref: ./paths/allocations_id.yaml
  /v1.0/allocations/{id}/process:
    $ref: ./paths/allocations_id_process.yaml
  /v1.0/allocationlines:
    $ref: ./paths/allocationlines.yaml
  /v1.0/allocationlines/{id}:
    $ref: ./paths/allocationlines_id.yaml
  /v1.0/productprices:
    $ref: ./paths/productprices.yaml
  /v1.0/productprices/{idProduct}/{idPriceListVersion}:
    $ref: ./paths/productprices_id_id.yaml
  /v1.0/storages:
    $ref: ./paths/storages.yaml
  /v1.0/storages/{idProduct}:
    $ref: ./paths/storages_id.yaml
  /v1.0/storages/{idProduct}/{idLocator}:
    $ref: ./paths/storages_id_id.yaml
  /v1.0/warehouses:
    $ref: ./paths/warehouses.yaml
  /v1.0/warehouses/{id}:
    $ref: ./paths/warehouses_id.yaml
  /v1.0/locators:
    $ref: ./paths/locators.yaml
  /v1.0/locators/{id}:
    $ref: ./paths/locators_id.yaml
  /v1.0/inventories:
    $ref: ./paths/inventories.yaml
  /v1.0/inventories/{id}:
    $ref: ./paths/inventories_id.yaml
  /v1.0/inventories/{id}/process:
    $ref: ./paths/inventories_id_process.yaml
  /v1.0/inventorylines:
    $ref: ./paths/inventorylines.yaml
  /v1.0/inventorylines/{id}:
    $ref: ./paths/inventorylines_id.yaml
  /v1.0/locations:
    $ref: ./paths/locations.yaml
  /v1.0/locations/{id}:
    $ref: ./paths/locations_id.yaml
  /v1.0/bpartnerlocations:
    $ref: ./paths/bpartnerlocations.yaml
  /v1.0/bpartnerlocations/{id}:
    $ref: ./paths/bpartnerlocations_id.yaml
  /v1.0/users:
    $ref: ./paths/users.yaml
  /v1.0/users/{id}:
    $ref: ./paths/users_id.yaml
  /v1.0/productlines:
    $ref: ./paths/productlines.yaml
  /v1.0/productlines/{id}:
    $ref: ./paths/productlines_id.yaml
  /v1.0/productgamas:
    $ref: ./paths/productgamas.yaml
  /v1.0/productgamas/{id}:
    $ref: ./paths/productgamas_id.yaml
  /v1.0/productcategories:
    $ref: ./paths/productcategories.yaml
  /v1.0/productcategories/{id}:
    $ref: ./paths/productcategories_id.yaml
  /v1.0/productfamilies:
    $ref: ./paths/productfamilies.yaml
  /v1.0/productfamilies/{id}:
    $ref: ./paths/productfamilies_id.yaml
  /v1.0/taxcategories:
    $ref: ./paths/taxcategories.yaml
  /v1.0/taxcategories/{id}:
    $ref: ./paths/taxcategories_id.yaml
  /v1.0/taxes:
    $ref: ./paths/taxes.yaml
  /v1.0/taxes/{id}:
    $ref: ./paths/taxes_id.yaml
  /v1.0/doctypes:
    $ref: ./paths/doctypes.yaml
  /v1.0/doctypes/{id}:
    $ref: ./paths/doctypes_id.yaml
  /v1.0/orgs:
    $ref: ./paths/orgs.yaml
  /v1.0/orgs/{id}:
    $ref: ./paths/orgs_id.yaml
  /v1.0/orgpercepcions:
    $ref: ./paths/orgpercepcions.yaml
  /v1.0/orgpercepcions/{id}:
    $ref: ./paths/orgpercepcions_id.yaml
  /v1.0/pos:
    $ref: ./paths/pos.yaml
  /v1.0/pos/{id}:
    $ref: ./paths/pos_id.yaml
  /v1.0/pospaymentmediums:
    $ref: ./paths/pospaymentmediums.yaml
  /v1.0/pospaymentmediums/{id}:
    $ref: ./paths/pospaymentmediums_id.yaml
  /v1.0/paymentterms:
    $ref: ./paths/paymentterms.yaml
  /v1.0/paymentterms/{id}:
    $ref: ./paths/paymentterms_id.yaml
  /v1.0/payschedules:
    $ref: ./paths/payschedules.yaml
  /v1.0/payschedules/{id}:
    $ref: ./paths/payschedules_id.yaml
  /v1.0/letrascomprobante:
    $ref: ./paths/letrascomprobante.yaml
  /v1.0/letrascomprobante/{id}:
    $ref: ./paths/letrascomprobante_id.yaml
  /v1.0/letrasaceptaiva:
    $ref: ./paths/letrasaceptaiva.yaml
  /v1.0/letrasaceptaiva/{id}:
    $ref: ./paths/letrasaceptaiva_id.yaml
  /v1.0/pricelists:
    $ref: ./paths/pricelists.yaml
  /v1.0/pricelists/{id}:
    $ref: ./paths/pricelists_id.yaml
  /v1.0/pricelistversions:
    $ref: ./paths/pricelistversions.yaml
  /v1.0/pricelistversions/{id}:
    $ref: ./paths/pricelistversions_id.yaml
  /v1.0/banks:
    $ref: ./paths/banks.yaml
  /v1.0/banks/{id}:
    $ref: ./paths/banks_id.yaml
  /v1.0/bankaccounts:
    $ref: ./paths/bankaccounts.yaml
  /v1.0/bankaccounts/{id}:
    $ref: ./paths/bankaccounts_id.yaml
  /v1.0/uoms:
    $ref: ./paths/uoms.yaml
  /v1.0/uoms/{id}:
    $ref: ./paths/uoms_id.yaml
  /v1.0/currencies:
    $ref: ./paths/currencies.yaml
  /v1.0/currencies/{id}:
    $ref: ./paths/currencies_id.yaml
  /v1.0/conversionrates:
    $ref: ./paths/conversionrates.yaml
  /v1.0/conversionrates/{id}:
    $ref: ./paths/conversionrates_id.yaml
  /v1.0/cashbooks:
    $ref: ./paths/cashbooks.yaml
  /v1.0/cashbooks/{id}:
    $ref: ./paths/cashbooks_id.yaml
  /v1.0/cash:
    $ref: ./paths/cash.yaml
  /v1.0/cash/{id}:
    $ref: ./paths/cash_id.yaml
  /v1.0/cash/{id}/process:
    $ref: ./paths/cash_id_process.yaml
  /v1.0/documentdiscounts:
    $ref: ./paths/documentdiscounts.yaml
  /v1.0/documentdiscounts/{id}:
    $ref: ./paths/documentdiscounts_id.yaml
  /v1.0/discountschemas:
    $ref: ./paths/discountschemas.yaml
  /v1.0/discountschemas/{id}:
    $ref: ./paths/discountschemas_id.yaml
  /v1.0/discountschemabreaks:
    $ref: ./paths/discountschemabreaks.yaml
  /v1.0/discountschemabreaks/{id}:
    $ref: ./paths/discountschemabreaks_id.yaml
  /v1.0/discountconfigs:
    $ref: ./paths/discountconfigs.yaml
  /v1.0/discountconfigs/{id}:
    $ref: ./paths/discountconfigs_id.yaml
  /v1.0/combos:
    $ref: ./paths/combos.yaml
  /v1.0/combos/{id}:
    $ref: ./paths/combos_id.yaml
  /v1.0/combolines:
    $ref: ./paths/combolines.yaml
  /v1.0/combolines/{id}:
    $ref: ./paths/combolines_id.yaml
  /v1.0/entidadesfinancieras:
    $ref: ./paths/entidadesfinancieras.yaml
  /v1.0/entidadesfinancieras/{id}:
    $ref: ./paths/entidadesfinancieras_id.yaml
  /v1.0/entidadfinancieraplanes:
    $ref: ./paths/entidadfinancieraplanes.yaml
  /v1.0/entidadfinancieraplanes/{id}:
    $ref: ./paths/entidadfinancieraplanes_id.yaml
  /v1.0/posjournals:
    $ref: ./paths/posjournals.yaml
  /v1.0/posjournals/{id}:
    $ref: ./paths/posjournals_id.yaml
  /v1.0/posjournals/{id}/process:
    $ref: ./paths/posjournals_id_process.yaml
  /v1.0/controladoresfiscales:
    $ref: ./paths/controladoresfiscales.yaml
  /v1.0/controladoresfiscales/{id}:
    $ref: ./paths/controladoresfiscales_id.yaml
  /v1.0/checkcuitcontrols:
    $ref: ./paths/checkcuitcontrols.yaml
  /v1.0/checkcuitcontrols/{id}:
    $ref: ./paths/checkcuitcontrols_id.yaml
  /v1.0/roles:
    $ref: ./paths/roles.yaml
  /v1.0/roles/{id}:
    $ref: ./paths/roles_id.yaml
  /v1.0/userroles:
    $ref: ./paths/userroles.yaml
  /v1.0/userroles/{idUser}/{idRole}:
    $ref: ./paths/userroles_id_id.yaml
  /v1.0/preferences:
    $ref: ./paths/preferences.yaml
  /v1.0/preferences/{id}:
    $ref: ./paths/preferences_id.yaml
  /v1.0/promotions:
    $ref: ./paths/promotions.yaml
  /v1.0/promotions/{id}:
    $ref: ./paths/promotions_id.yaml
  /v1.0/posletters:
    $ref: ./paths/posletters.yaml
  /v1.0/posletters/{id}:
    $ref: ./paths/posletters_id.yaml
  /v1.0/journals:
    $ref: ./paths/journals.yaml
  /v1.0/journals/{id}:
    $ref: ./paths/journals_id.yaml
  /v1.0/journals/{id}/process:
    $ref: ./paths/journals_id_process.yaml
  /v1.0/journallines:
    $ref: ./paths/journallines.yaml
  /v1.0/journallines/{id}:
    $ref: ./paths/journallines_id.yaml
  /v1.0/elementvalues:
    $ref: ./paths/elementvalues.yaml
  /v1.0/elementvalues/{id}:
    $ref: ./paths/elementvalues_id.yaml
  /v1.0/acctschemas:
    $ref: ./paths/acctschemas.yaml
  /v1.0/acctschemas/{id}:
    $ref: ./paths/acctschemas_id.yaml
  /v1.0/glcategories:
    $ref: ./paths/glcategories.yaml
  /v1.0/glcategories/{id}:
    $ref: ./paths/glcategories_id.yaml
  /v1.0/periods:
    $ref: ./paths/periods.yaml
  /v1.0/periods/{id}:
    $ref: ./paths/periods_id.yaml
  /v1.0/validcombinations:
    $ref: ./paths/validcombinations.yaml
  /v1.0/validcombinations/{id}:
    $ref: ./paths/validcombinations_id.yaml
# metadata end-points
  /v1.0/tables:
    $ref: ./paths/tables.yaml
  /v1.0/tables/{id}:
    $ref: ./paths/tables_id.yaml
  /v1.0/columns:
    $ref: ./paths/columns.yaml
  /v1.0/columns/{id}:
    $ref: ./paths/columns_id.yaml
  /v1.0/windows:
    $ref: ./paths/windows.yaml
  /v1.0/windows/{id}:
    $ref: ./paths/windows_id.yaml
  /v1.0/tabs:
    $ref: ./paths/tabs.yaml
  /v1.0/tabs/{id}:
    $ref: ./paths/tabs_id.yaml
  /v1.0/fields:
    $ref: ./paths/fields.yaml
  /v1.0/fields/{id}:
    $ref: ./paths/fields_id.yaml
  /v1.0/fieldgroups:
    $ref: ./paths/fieldgroups.yaml
  /v1.0/fieldgroups/{id}:
    $ref: ./paths/fieldgroups_id.yaml
  /v1.0/elements:
    $ref: ./paths/elements.yaml
  /v1.0/elements/{id}:
    $ref: ./paths/elements_id.yaml
  /v1.0/messages:
    $ref: ./paths/messages.yaml
  /v1.0/messages/{id}:
    $ref: ./paths/messages_id.yaml
  /v1.0/references:
    $ref: ./paths/references.yaml
  /v1.0/references/{id}:
    $ref: ./paths/references_id.yaml
  /v1.0/reflists:
    $ref: ./paths/reflists.yaml
  /v1.0/reflists/{id}:
    $ref: ./paths/reflists_id.yaml
  /v1.0/reftables:
    $ref: ./paths/reftables.yaml
  /v1.0/reftables/{id}:
    $ref: ./paths/reftables_id.yaml
  /v1.0/valrules:
    $ref: ./paths/valrules.yaml
  /v1.0/valrules/{id}:
    $ref: ./paths/valrules_id.yaml
  /v1.0/tabletrls:
    $ref: ./paths/table_trls.yaml
  /v1.0/tabletrls/{idTable}/{idLanguage}:
    $ref: ./paths/table_trls_id_id.yaml
  /v1.0/columntrls:
    $ref: ./paths/column_trls.yaml
  /v1.0/columntrls/{idColumn}/{idLanguage}:
    $ref: ./paths/column_trls_id_id.yaml
  /v1.0/windowtrls:
    $ref: ./paths/window_trls.yaml
  /v1.0/windowtrls/{idWindow}/{idLanguage}:
    $ref: ./paths/window_trls_id_id.yaml
  /v1.0/tabtrls:
    $ref: ./paths/tab_trls.yaml
  /v1.0/tabtrls/{idTab}/{idLanguage}:
    $ref: ./paths/tab_trls_id_id.yaml
  /v1.0/fieldtrls:
    $ref: ./paths/field_trls.yaml
  /v1.0/fieldtrls/{idField}/{idLanguage}:
    $ref: ./paths/field_trls_id_id.yaml
  /v1.0/elementtrls:
    $ref: ./paths/element_trls.yaml
  /v1.0/elementtrls/{idElement}/{idLanguage}:
    $ref: ./paths/element_trls_id_id.yaml
  /v1.0/messagetrls:
    $ref: ./paths/message_trls.yaml
  /v1.0/messagetrls/{idMessage}/{idLanguage}:
    $ref: ./paths/message_trls_id_id.yaml
  /v1.0/fieldgrouptrls:
    $ref: ./paths/fieldgroup_trls.yaml
  /v1.0/fieldgrouptrls/{idFieldGroup}/{idLanguage}:
    $ref: ./paths/fieldgroup_trls_id_id.yaml
  /v1.0/referencetrls:
    $ref: ./paths/reference_trls.yaml
  /v1.0/referencetrls/{idReference}/{idLanguage}:
    $ref: ./paths/reference_trls_id_id.yaml
  /v1.0/reflisttrls:
    $ref: ./paths/reflist_trls.yaml
  /v1.0/reflisttrls/{idRefList}/{idLanguage}:
    $ref: ./paths/reflist_trls_id_id.yaml
# augmented metadata end-points
  /v1.0/windows/{id}/schema:
    $ref: ./paths/windows_id_schema.yaml
  /v1.0/windows/options:
    $ref: ./paths/windows_options.yaml
  /v1.0/columns/{id}/lookup:
    $ref: ./paths/columns_id_lookup.yaml
  /v1.0/roleoptions:
    $ref: ./paths/roles_options.yaml