get:
  summary: Retorna la lista de configuracion de descuentos
  tags:
    - "discountconfig"
  description: Retorna la lista completa de configuracion de descuentos
  operationId: getAllDiscountConfigs
  parameters:
    - in: query
      name: filter
      schema:
        type: string
      description: Criterio de filtrado
    - in: query
      name: fields
      schema:
        type: string
      description: Campos a recuperar
    - in: query
      name: sort
      schema:
        type: string
      description: Criterio de ordenado
    - in: query
      name: limit
      schema:
        type: integer
      description: Limite de elementos a retornar por pagina
    - in: query
      name: page
      schema:
        type: integer
      description: Numero de pagina
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../model/discountconfig.yaml#/components/schemas/DiscountConfig'
post:
  summary: Nueva configuracion de descuentos
  tags:
    - "discountconfig"
  description: Agrega una nueva configuracion de descuentos
  operationId: addDiscountConfig
  responses:
    "200":
      description: OK. ID de la configuracion de descuentos es retornado
      content:
        text/plain:
          schema:
            type: string
    "409":
      description: Imposible insertar
      content:
        text/plain:
          schema:
            type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          $ref: '../model/discountconfig.yaml#/components/schemas/DiscountConfig'
