get:
  summary: Retorna la lista de marcas de articulos
  tags:
    - "productfamilies"
  description: Retorna la lista completa de marcas de articulos
  operationId: getAllProductFamilies
  parameters:
    - in: query
      name: filter
      schema:
        type: string
      description: Criterio de filtrado
    - in: query
      name: fields
      schema:
        type: string
      description: Campos a recuperar
    - in: query
      name: sort
      schema:
        type: string
      description: Criterio de ordenado
    - in: query
      name: limit
      schema:
        type: integer
      description: Limite de elementos a retornar por pagina
    - in: query
      name: page
      schema:
        type: integer
      description: Numero de pagina
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../model/productfamilies.yaml#/components/schemas/ProductFamilies'
post:
  summary: Nueva marca de articulo
  tags:
    - "productfamilies"
  description: Agrega una nueva marca de articulo
  operationId: addProductFamily
  responses:
    "200":
      description: OK. ID de la marca de artiulo es retornado
      content:
        text/plain:
          schema:
            type: string
    "409":
      description: Imposible insertar
      content:
        text/plain:
          schema:
            type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          $ref: '../model/productfamilies.yaml#/components/schemas/ProductFamilies'
