get:
  summary: Retrieve all product prices
  tags:
    - "productprice"
  description: Retorna la lista completa de precios
  operationId: getAllProductPrices
  parameters:
    - in: query
      name: filter
      schema:
        type: string
      description: Criterio de filtrado
    - in: query
      name: fields
      schema:
        type: string
      description: Campos a recuperar
    - in: query
      name: sort
      schema:
        type: string
      description: Criterio de ordenado
    - in: query
      name: limit
      schema:
        type: integer
      description: Limite de elementos a retornar por pagina
    - in: query
      name: page
      schema:
        type: integer
      description: Numero de pagina
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../model/productprice.yaml#/components/schemas/ProductPrice'
post:
  summary: Nuevo precio de articulo
  tags:
    - "productprice"
  description: Agrega un nuevo precio a un articulo
  operationId: addProductPrice
  responses:
    "200":
      description: OK. ID del precio de producto creado es retornado, el cual es formato por su ID de Producto y ID de Version de Lista de Precio
      content:
        text/plain:
          schema:
            type: string
    "409":
      description: Imposible insertar
      content:
        text/plain:
          schema:
            type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          $ref: '../model/productprice.yaml#/components/schemas/ProductPrice'
