get:
  summary: Recupera una marca de producto en particular
  tags:
    - "productfamilies"
  parameters:
    - name: id
      in: path
      description: ID de la marca de articulo
      required: true
      schema:
        type: integer
  description: Recupera la informacion de una marca de articulo en particular
  operationId: retrieveProductFamily
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: '../model/productfamilies.yaml#/components/schemas/ProductFamilies'
delete:
  summary: Elimina una marca de articulo
  tags:
    - "productfamilies"
  parameters:
    - name: id
      in: path
      description: ID de la marca de articulo
      required: true
      schema:
        type: integer
  description: Elimina una marca de articulo existente
  operationId: deleteProductFamily
  responses:
    "409":
      description: Imposible eliminar
      content:
        text/plain:
          schema:
            type: string
    "404":
      description: No encontrado
      content:
        text/plain:
          schema:
            type: string
    "204":
      description: OK
      content:
        text/plain:
          schema:
            type: string
put:
  summary: Actualiza por completo una marca de articulo existente
  tags:
    - "productfamilies"
  operationId: updateProductFamily
  parameters:
    - name: id
      in: path
      description: ID de la marca de articulo a actualizar
      required: true
      schema:
        type: integer
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          $ref: '../model/productfamilies.yaml#/components/schemas/ProductFamilies'
  responses:
    "200":
      description: OK
      content:
        text/plain:
          schema:
            type: string
    "409":
      description: Imposible actualizar
      content:
        text/plain:
          schema:
            type: string
    "404":
      description: No encontrado
      content:
        text/plain:
          schema:
            type: string