get:
  summary: Recupera un producto en particular
  tags:
    - "product"
  parameters:
    - name: id
      in: path
      description: ID del articulo
      required: true
      schema:
        type: integer
  description: Recupera la informacion de un articulo en particular
  operationId: retrieveProduct
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: '../model/product.yaml#/components/schemas/Product'
delete:
  summary: Elimina un articulo
  tags:
    - "product"
  parameters:
    - name: id
      in: path
      description: ID de articulo
      required: true
      schema:
        type: integer
  description: Elimina un articulo existente
  operationId: deleteProduct
  responses:
    "409":
      description: Imposible eliminar
      content:
        text/plain:
          schema:
            type: string
    "404":
      description: No encontrado
      content:
        text/plain:
          schema:
            type: string
    "204":
      description: OK
      content:
        text/plain:
          schema:
            type: string
put:
  summary: Actualiza por completo un articulo existente
  tags:
    - "product"
  operationId: updateProduct
  parameters:
    - name: id
      in: path
      description: ID del articulo a actualizar
      required: true
      schema:
        type: integer
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          $ref: '../model/product.yaml#/components/schemas/Product'
  responses:
    "200":
      description: OK
      content:
        text/plain:
          schema:
            type: string
    "409":
      description: Imposible actualizar
      content:
        text/plain:
          schema:
            type: string
    "404":
      description: No encontrado
      content:
        text/plain:
          schema:
            type: string