get:
  summary: Recupera una subfamilia de producto en particular
  tags:
    - "productcategories"
  parameters:
    - name: id
      in: path
      description: ID de la subfamilia de articulo
      required: true
      schema:
        type: integer
  description: Recupera la informacion de una subfamilia de articulo en particular
  operationId: retrieveProductCategory
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: '../model/productcategories.yaml#/components/schemas/ProductCategories'
delete:
  summary: Elimina una subfamilia de articulo
  tags:
    - "productcategories"
  parameters:
    - name: id
      in: path
      description: ID de la subfamilia de articulo
      required: true
      schema:
        type: integer
  description: Elimina una subfamilia de articulo existente
  operationId: deleteProductCategory
  responses:
    "409":
      description: Imposible eliminar
      content:
        text/plain:
          schema:
            type: string
    "404":
      description: No encontrado
      content:
        text/plain:
          schema:
            type: string
    "204":
      description: OK
      content:
        text/plain:
          schema:
            type: string
put:
  summary: Actualiza por completo una subfamilia de articulo existente
  tags:
    - "productcategories"
  operationId: updateProductCategory
  parameters:
    - name: id
      in: path
      description: ID de la subfamilia de articulo a actualizar
      required: true
      schema:
        type: integer
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          $ref: '../model/productcategories.yaml#/components/schemas/ProductCategories'
  responses:
    "200":
      description: OK
      content:
        text/plain:
          schema:
            type: string
    "409":
      description: Imposible actualizar
      content:
        text/plain:
          schema:
            type: string
    "404":
      description: No encontrado
      content:
        text/plain:
          schema:
            type: string