get:
  summary: Recupera una familia de producto en particular
  tags:
    - "productgamas"
  parameters:
    - name: id
      in: path
      description: ID de la familia de articulo
      required: true
      schema:
        type: integer
  description: Recupera la informacion de una familia de articulo en particular
  operationId: retrieveProductGama
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            $ref: '../model/productgamas.yaml#/components/schemas/ProductGamas'
delete:
  summary: Elimina una familia de articulo
  tags:
    - "productgamas"
  parameters:
    - name: id
      in: path
      description: ID de la familia de articulo
      required: true
      schema:
        type: integer
  description: Elimina una familia de articulo existente
  operationId: deleteProductGama
  responses:
    "409":
      description: Imposible eliminar
      content:
        text/plain:
          schema:
            type: string
    "404":
      description: No encontrado
      content:
        text/plain:
          schema:
            type: string
    "204":
      description: OK
      content:
        text/plain:
          schema:
            type: string
put:
  summary: Actualiza por completo una familia de articulo existente
  tags:
    - "productgamas"
  operationId: updateProductGama
  parameters:
    - name: id
      in: path
      description: ID de la familia de articulo a actualizar
      required: true
      schema:
        type: integer
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          $ref: '../model/productgamas.yaml#/components/schemas/ProductGamas'
  responses:
    "200":
      description: OK
      content:
        text/plain:
          schema:
            type: string
    "409":
      description: Imposible actualizar
      content:
        text/plain:
          schema:
            type: string
    "404":
      description: No encontrado
      content:
        text/plain:
          schema:
            type: string