/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.libertya.api.stub.iface;

import org.libertya.api.stub.model.CommissionConcepts;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Validated
public interface CommissionconceptApi {

    Logger log = LoggerFactory.getLogger(CommissionconceptApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @Operation(summary = "Retorna las filas de comisiones de la liquidacion", description = "Retorna las filas de comisiones de la liquidacion de una liquidacion de tarjetas.  NO HACE FALTA CREARLAS. Al crear la cabecera, el modelo ejecuta generateAllChildrens() y deja una fila en cero por cada concepto activo del maestro correspondiente. Una fila por cada concepto de tipo comision. El concepto se identifica por c_cardsettlementconcepts_id, que se resuelve con GET /v1.0/cardsettlementconcepts?filter=type='CO'.  El uso normal es listar las filas de una liquidacion para saber que concepto es cada una, y despues cargar el importe con PUT /v1.0/commissionconcepts/{id}:       GET /v1.0/commissionconcepts?filter=c_creditcardsettlement_id=1234   Cuelgan directo de C_CreditCardSettlement, no del filtro de cupones. ", security = {
        @SecurityRequirement(name = "jwtAuth")    }, tags={ "commissionconcept" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CommissionConcepts.class)))) })
    @RequestMapping(value = "/v1.0/commissionconcepts",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<CommissionConcepts>> getAllCommissionConcepts(@Parameter(in = ParameterIn.QUERY, description = "Criterio de filtrado" ,schema=@Schema()) @Valid @RequestParam(value = "filter", required = false) String filter, @Parameter(in = ParameterIn.QUERY, description = "Campos a recuperar" ,schema=@Schema()) @Valid @RequestParam(value = "fields", required = false) String fields, @Parameter(in = ParameterIn.QUERY, description = "Criterio de ordenado" ,schema=@Schema()) @Valid @RequestParam(value = "sort", required = false) String sort, @Parameter(in = ParameterIn.QUERY, description = "Limite de elementos a retornar por pagina" ,schema=@Schema()) @Valid @RequestParam(value = "limit", required = false) Integer limit, @Parameter(in = ParameterIn.QUERY, description = "Numero de pagina" ,schema=@Schema()) @Valid @RequestParam(value = "page", required = false) Integer page) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {\n  \"c_creditcardsettlement_id\" : 2,\n  \"amount\" : 1.4658129805029452,\n  \"updatedby\" : 9,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_cardsettlementconcepts_id\" : 5,\n  \"c_commissionconcepts_id\" : 5,\n  \"createdby\" : 7,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\"\n}, {\n  \"c_creditcardsettlement_id\" : 2,\n  \"amount\" : 1.4658129805029452,\n  \"updatedby\" : 9,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_cardsettlementconcepts_id\" : 5,\n  \"c_commissionconcepts_id\" : 5,\n  \"createdby\" : 7,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\"\n} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default CommissionconceptApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @Operation(summary = "Recupera una fila de comisiones de la liquidacion en particular", description = "Recupera la informacion de una fila de comisiones de la liquidacion en particular", security = {
        @SecurityRequirement(name = "jwtAuth")    }, tags={ "commissionconcept" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation = CommissionConcepts.class))),
        
        @ApiResponse(responseCode = "404", description = "No encontrado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))) })
    @RequestMapping(value = "/v1.0/commissionconcepts/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<CommissionConcepts> retrieveCommissionConcepts(@Parameter(in = ParameterIn.PATH, description = "ID del registro", required=true, schema=@Schema()) @PathVariable("id") Integer id) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"c_creditcardsettlement_id\" : 2,\n  \"amount\" : 1.4658129805029452,\n  \"updatedby\" : 9,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_cardsettlementconcepts_id\" : 5,\n  \"c_commissionconcepts_id\" : 5,\n  \"createdby\" : 7,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\"\n}", CommissionConcepts.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default CommissionconceptApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @Operation(summary = "Actualiza una fila de comisiones de la liquidacion", description = "Actualiza una fila ya existente. El uso principal es cargarle el importe, que la fila trae en cero desde que el modelo la genero:       PUT /v1.0/commissionconcepts/{id}    con body {\"amount\": 1234.56}   Al guardar, el modelo recalcula solo el total CommissionAmount de la cabecera de la liquidacion. Ese recalculo lo hace la clase del core, no esta API: si el total de la cabecera no cambia despues de un PUT exitoso, el problema esta en el core cargado, no aca.  No se expone POST: las filas ya vienen creadas. El unico caso que quedaria sin cubrir es un concepto dado de alta en el maestro despues de creada la liquidacion. ", security = {
        @SecurityRequirement(name = "jwtAuth")    }, tags={ "commissionconcept" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "text/plain", schema = @Schema(implementation = String.class))),
        
        @ApiResponse(responseCode = "409", description = "Imposible actualizar", content = @Content(mediaType = "text/plain", schema = @Schema(implementation = String.class))),
        
        @ApiResponse(responseCode = "404", description = "No encontrado", content = @Content(mediaType = "text/plain", schema = @Schema(implementation = String.class))) })
    @RequestMapping(value = "/v1.0/commissionconcepts/{id}",
        produces = { "text/plain" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    default ResponseEntity<String> updateCommissionConcepts(@Parameter(in = ParameterIn.PATH, description = "ID del registro a actualizar", required=true, schema=@Schema()) @PathVariable("id") Integer id, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody CommissionConcepts body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("\"\"", String.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default CommissionconceptApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}

