/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.libertya.api.stub.iface;

import org.libertya.api.stub.model.NumeroComercio;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Validated
public interface NumerocomercioApi {

    Logger log = LoggerFactory.getLogger(NumerocomercioApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @Operation(summary = "Retorna la lista de numeros de comercio", description = "Retorna la lista de numeros de comercio. Recurso de solo lectura: el mantenimiento se hace desde Libertya. Es el maestro que resuelve, para una liquidacion de tarjetas, la entidad comercial (c_bpartner_id) contra la que se emite y las cuentas bancarias asociadas. El c_bpartner_id NO se deduce del adquirente: un mismo adquirente puede operar contra varias entidades comerciales segun el comercio. Tabla exclusiva del diccionario de Tehuelche. ", security = {
        @SecurityRequirement(name = "jwtAuth")    }, tags={ "numerocomercio" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = NumeroComercio.class)))) })
    @RequestMapping(value = "/v1.0/numeroscomercio",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<NumeroComercio>> getAllNumerosComercio(@Parameter(in = ParameterIn.QUERY, description = "Criterio de filtrado" ,schema=@Schema()) @Valid @RequestParam(value = "filter", required = false) String filter, @Parameter(in = ParameterIn.QUERY, description = "Campos a recuperar" ,schema=@Schema()) @Valid @RequestParam(value = "fields", required = false) String fields, @Parameter(in = ParameterIn.QUERY, description = "Criterio de ordenado" ,schema=@Schema()) @Valid @RequestParam(value = "sort", required = false) String sort, @Parameter(in = ParameterIn.QUERY, description = "Limite de elementos a retornar por pagina" ,schema=@Schema()) @Valid @RequestParam(value = "limit", required = false) Integer limit, @Parameter(in = ParameterIn.QUERY, description = "Numero de pagina" ,schema=@Schema()) @Valid @RequestParam(value = "page", required = false) Integer page) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {\n  \"updatedby\" : 9,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"m_numerocomercio_id\" : 7,\n  \"financingservice\" : \"financingservice\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_bankaccount_id\" : 1,\n  \"numerocomercio\" : \"numerocomercio\",\n  \"c_bankaccount_settlement_id\" : 5,\n  \"createdby\" : 2,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"adquirente\" : \"adquirente\",\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\",\n  \"value\" : \"value\",\n  \"c_bpartner_id\" : 5\n}, {\n  \"updatedby\" : 9,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"m_numerocomercio_id\" : 7,\n  \"financingservice\" : \"financingservice\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_bankaccount_id\" : 1,\n  \"numerocomercio\" : \"numerocomercio\",\n  \"c_bankaccount_settlement_id\" : 5,\n  \"createdby\" : 2,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"adquirente\" : \"adquirente\",\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\",\n  \"value\" : \"value\",\n  \"c_bpartner_id\" : 5\n} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default NumerocomercioApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @Operation(summary = "Recupera un numero de comercio en particular", description = "Recupera la informacion de un numero de comercio en particular", security = {
        @SecurityRequirement(name = "jwtAuth")    }, tags={ "numerocomercio" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation = NumeroComercio.class))) })
    @RequestMapping(value = "/v1.0/numeroscomercio/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<NumeroComercio> retrieveNumeroComercio(@Parameter(in = ParameterIn.PATH, description = "ID del registro", required=true, schema=@Schema()) @PathVariable("id") Integer id) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"updatedby\" : 9,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"m_numerocomercio_id\" : 7,\n  \"financingservice\" : \"financingservice\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_bankaccount_id\" : 1,\n  \"numerocomercio\" : \"numerocomercio\",\n  \"c_bankaccount_settlement_id\" : 5,\n  \"createdby\" : 2,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"adquirente\" : \"adquirente\",\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\",\n  \"value\" : \"value\",\n  \"c_bpartner_id\" : 5\n}", NumeroComercio.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default NumerocomercioApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}

