/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.libertya.api.stub.iface;

import org.libertya.api.stub.model.RetencionSchema;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Validated
public interface RetencionschemaApi {

    Logger log = LoggerFactory.getLogger(RetencionschemaApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @Operation(summary = "Retorna la lista de esquemas de retencion", description = "Retorna la lista de esquemas de retencion. Recurso de solo lectura: el mantenimiento se hace desde Libertya. Es el maestro que resuelve, para una liquidacion de tarjetas, contra que esquema se imputa cada fila de C_WithholdingSettlement.  Para las retenciones SUFRIDAS (las de una liquidacion de tarjetas) hay que filtrar por retencionapplication='S'; el valor 'E' son las emitidas, que no aplican aca. El filtro NO se aplica del lado del servidor a proposito, para no limitar otros usos del maestro:       GET /v1.0/retencionschemas?filter=retencionapplication='S' AND isactive='Y'   c_region_id viaja en la propia fila del esquema, no hay que resolverlo por separado. ", security = {
        @SecurityRequirement(name = "jwtAuth")    }, tags={ "retencionschema" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = RetencionSchema.class)))) })
    @RequestMapping(value = "/v1.0/retencionschemas",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<RetencionSchema>> getAllRetencionSchemas(@Parameter(in = ParameterIn.QUERY, description = "Criterio de filtrado" ,schema=@Schema()) @Valid @RequestParam(value = "filter", required = false) String filter, @Parameter(in = ParameterIn.QUERY, description = "Campos a recuperar" ,schema=@Schema()) @Valid @RequestParam(value = "fields", required = false) String fields, @Parameter(in = ParameterIn.QUERY, description = "Criterio de ordenado" ,schema=@Schema()) @Valid @RequestParam(value = "sort", required = false) String sort, @Parameter(in = ParameterIn.QUERY, description = "Limite de elementos a retornar por pagina" ,schema=@Schema()) @Valid @RequestParam(value = "limit", required = false) Integer limit, @Parameter(in = ParameterIn.QUERY, description = "Numero de pagina" ,schema=@Schema()) @Valid @RequestParam(value = "page", required = false) Integer page) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("[ {\n  \"ismanual\" : true,\n  \"updatedby\" : 3,\n  \"c_retencionschema_id\" : 7,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_retenciontype_id\" : 9,\n  \"description\" : \"description\",\n  \"c_region_id\" : 5,\n  \"c_bpartner_recaudador_id\" : 1,\n  \"c_retencionprocessor_id\" : 2,\n  \"retencionapplication\" : \"retencionapplication\",\n  \"createdby\" : 5,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"name\" : \"name\",\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\",\n  \"value\" : \"value\"\n}, {\n  \"ismanual\" : true,\n  \"updatedby\" : 3,\n  \"c_retencionschema_id\" : 7,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_retenciontype_id\" : 9,\n  \"description\" : \"description\",\n  \"c_region_id\" : 5,\n  \"c_bpartner_recaudador_id\" : 1,\n  \"c_retencionprocessor_id\" : 2,\n  \"retencionapplication\" : \"retencionapplication\",\n  \"createdby\" : 5,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"name\" : \"name\",\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\",\n  \"value\" : \"value\"\n} ]", List.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default RetencionschemaApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @Operation(summary = "Recupera un esquema de retencion en particular", description = "Recupera la informacion de un esquema de retencion en particular", security = {
        @SecurityRequirement(name = "jwtAuth")    }, tags={ "retencionschema" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation = RetencionSchema.class))),
        
        @ApiResponse(responseCode = "404", description = "No encontrado", content = @Content(mediaType = "application/json", schema = @Schema(implementation = String.class))) })
    @RequestMapping(value = "/v1.0/retencionschemas/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<RetencionSchema> retrieveRetencionSchema(@Parameter(in = ParameterIn.PATH, description = "ID del registro", required=true, schema=@Schema()) @PathVariable("id") Integer id) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"ismanual\" : true,\n  \"updatedby\" : 3,\n  \"c_retencionschema_id\" : 7,\n  \"ad_org_id\" : 6,\n  \"created\" : \"created\",\n  \"isactive\" : true,\n  \"referencedvalues\" : [ null, null ],\n  \"c_retenciontype_id\" : 9,\n  \"description\" : \"description\",\n  \"c_region_id\" : 5,\n  \"c_bpartner_recaudador_id\" : 1,\n  \"c_retencionprocessor_id\" : 2,\n  \"retencionapplication\" : \"retencionapplication\",\n  \"createdby\" : 5,\n  \"additionalvalues\" : [ {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  }, {\n    \"value\" : \"value\",\n    \"key\" : \"key\"\n  } ],\n  \"name\" : \"name\",\n  \"ad_client_id\" : 0,\n  \"updated\" : \"updated\",\n  \"value\" : \"value\"\n}", RetencionSchema.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default RetencionschemaApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}

