/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.libertya.api.stub.iface;

import org.libertya.api.stub.model.WindowRecordState;
import org.libertya.api.stub.model.WindowRecordStateRequest;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Validated
public interface WindowstateApi {

    Logger log = LoggerFactory.getLogger(WindowstateApi.class);

    default Optional<ObjectMapper> getObjectMapper(){
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest(){
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @Operation(summary = "Construye el estado inicial de un nuevo registro", description = "Resuelve en una única operación los valores iniciales y el estado efectivo de todos los campos de una pestaña dinámica. El contrato contempla DefaultValue, DisplayLogic y ReadOnlyLogic. ", security = {
        @SecurityRequirement(name = "jwtAuth")    }, tags={ "windowstate" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Estado inicial efectivo del nuevo registro", content = @Content(mediaType = "application/json", schema = @Schema(implementation = WindowRecordState.class))),
        
        @ApiResponse(responseCode = "404", description = "Pestaña inexistente") })
    @RequestMapping(value = "/v1.0/tabs/{id}/new-record",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<WindowRecordState> createTabNewRecordState(@Parameter(in = ParameterIn.PATH, description = "ID de la pestaña", required=true, schema=@Schema()) @PathVariable("id") Integer id, @Parameter(in = ParameterIn.DEFAULT, description = "", schema=@Schema()) @Valid @RequestBody WindowRecordStateRequest body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"values\" : {\n    \"key\" : \"values\"\n  },\n  \"fields\" : [ {\n    \"displayed\" : true,\n    \"ad_field_id\" : 0,\n    \"readonly\" : true,\n    \"columnname\" : \"columnname\"\n  }, {\n    \"displayed\" : true,\n    \"ad_field_id\" : 0,\n    \"readonly\" : true,\n    \"columnname\" : \"columnname\"\n  } ]\n}", WindowRecordState.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default WindowstateApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}

