components:
  schemas:
    ProductLines:
      type: object
      properties:
        ad_client_id:
          type: integer
          description: "Compañía o empresa que utiliza ésta instalación"
        ad_componentobjectuid:
          type: string
          description: " "
        ad_org_id:
          type: integer
          description: "Entidad organizacional dentro de la compañía"
        created:
          type: string
          description: "Fecha de creación de este registro"
        createdby:
          type: integer
          description: "Usuario que creó este registro"
        description:
          type: string
          description: "Descripción corta opcional del registro"
        isactive:
          type: boolean
          description: "El registro está activo en el sistema"
        isdefault:
          type: boolean
          description: "Valor Predeterminado"
        isselfservice:
          type: boolean
          description: "Disp. en Web"
        m_product_lines_id:
          type: integer
          description: " "
        name:
          type: string
          description: "Identificador alfanumérico de la Entidad"
        processed:
          type: boolean
          description: "El documento ha sido procesado"
        updated:
          type: string
          description: "Determina si el campo esta actualizado"
        updatedby:
          type: integer
          description: "Determina quien actualizó el campo"
        value:
          type: string
          description: "Clave de búsqueda para el registro en el formato requerido; debe ser única"
        additionalvalues:
          type: array
          items:
            $ref: './propertiesmap.yaml#/propertiesmap'
        referencedvalues:
          type: array
          items:
            $ref: './propertiesmap.yaml#/propertiesmap'
      required:
         - ad_client_id
         - ad_org_id
         - created
         - createdby
         - isactive
         - isdefault
         - isselfservice
         - m_product_lines_id
         - name
         - updated
         - updatedby
         - value
