components:
  schemas:
    Product:
      type: object
      properties:
        ad_client_id:
          type: integer
        ad_componentobjectuid:
          type: string
        ad_org_id:
          type: integer
        amortizationperc:
          type: number
        checkoutplace:
          type: string
        classification:
          type: string
        common_ref:
          type: number
        created:
          type: string
        createdby:
          type: integer
        c_revenuerecognition_id:
          type: integer
        c_subscriptiontype_id:
          type: integer
        c_taxcategory_id:
          type: integer
        c_uom_id:
          type: integer
        deliverytime_promised:
          type: number
        description:
          type: string
        descriptionurl:
          type: string
        discontinued:
          type: boolean
        discontinuedby:
          type: string
        documentnote:
          type: string
        guaranteedays:
          type: integer
        guaranteedaysmin:
          type: integer
        help:
          type: string
        imageurl:
          type: string
        isactive:
          type: boolean
        isbom:
          type: boolean
        isdropship:
          type: boolean
        ishelp:
          type: boolean
        isinventoried:
          type: boolean
        isinvoiceprintdetails:
          type: boolean
        ispicklistprintdetails:
          type: boolean
        ispurchased:
          type: boolean
        isselfservice:
          type: boolean
        issold:
          type: boolean
        isstocked:
          type: boolean
        issummary:
          type: boolean
        istoformule:
          type: boolean
        isverified:
          type: boolean
        iswebstorefeatured:
          type: boolean
        lowlevel:
          type: integer
        marketingblocked:
          type: boolean
        marketingblockeddescr:
          type: string
        m_attributeset_id:
          type: integer
        m_attributesetinstance_id:
          type: integer
        m_freightcategory_id:
          type: integer
        m_intrastatcode_id:
          type: number
        m_locator_id:
          type: integer
        m_product_category_id:
          type: integer
        m_product_family_id:
          type: integer
        m_product_id:
          type: integer
        name:
          type: string
        producttype:
          type: string
        r_mailtext_id:
          type: integer
        sales_order_min:
          type: number
        sales_order_pack:
          type: number
        salesrep_id:
          type: integer
        s_expensetype_id:
          type: integer
        shelfdepth:
          type: integer
        shelfheight:
          type: integer
        shelfwidth:
          type: integer
        sku:
          type: string
        s_resource_id:
          type: integer
        unitsperpallet:
          type: integer
        upc:
          type: string
        updated:
          type: string
        updatedby:
          type: integer
        value:
          type: string
        versionno:
          type: string
        volume:
          type: number
        weight:
          type: number
        yearlife:
          type: integer
        referencedvalues:
          type: array
          items:
            $ref: './propertiesmap.yaml#/propertiesmap'
      required:
         - ad_client_id
         - ad_org_id
         - amortizationperc
         - checkoutplace
         - created
         - createdby
         - c_taxcategory_id
         - c_uom_id
         - isactive
         - isbom
         - isdropship
         - isinventoried
         - isinvoiceprintdetails
         - ispicklistprintdetails
         - ispurchased
         - isselfservice
         - issold
         - isstocked
         - issummary
         - isverified
         - iswebstorefeatured
         - m_attributesetinstance_id
         - m_product_category_id
         - m_product_id
         - name
         - producttype
         - updated
         - updatedby
         - value
         - yearlife
